# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitstation', '0002_auto_20160902_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_habit_activity',
            name='user',
        ),
    ]
